# This file was generated by GoReleaser. DO NOT EDIT.
cask "mail-mcp" do
  name "mail-mcp"
  desc "MCP server providing programmatic access to macOS Mail.app"
  homepage "https://github.com/dastrobu/mail-mcp"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mail-mcp"

  on_macos do
    on_intel do
      url "https://github.com/dastrobu/mail-mcp/releases/download/v#{version}/mail-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "20588927082303bcbc2fc443e1c7461fc2b225fee78d820bb2ba17591b02e306"
    end
    on_arm do
      url "https://github.com/dastrobu/mail-mcp/releases/download/v#{version}/mail-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "032d6b3a793027877225fb0d09f1dbb8fcdeabe76f43c9ceea2b9ae0d7a13f48"
    end
  end

  caveats do
    "Apple Mail MCP Server has been installed!"
    ""
    "⚠️  IMPORTANT: For proper automation permissions, you should run this server"
    "via launchd or brew services (not from Terminal directly)."
    ""
    "Option 1: Use Homebrew Services (Standard)"
    "  brew services start mail-mcp"
    ""
    "Option 2: Use custom launchd service (for custom port/debug)"
    "  mail-mcp launchd create"
    ""
    "To remove the launchd service:"
    "  mail-mcp launchd remove"
    ""
    "Before uninstalling with 'brew uninstall mail-mcp':"
    "  1. Stop and remove the service: brew services stop mail-mcp OR mail-mcp launchd remove"
    "  2. Then run: brew uninstall mail-mcp"
    ""
    "For more information:"
    "  • README: https://github.com/dastrobu/mail-mcp#readme"
    "  • Docs: https://github.com/dastrobu/mail-mcp/tree/main/docs"
  end

  service "run [opt_bin/"mail-mcp", "run", "--transport=http"]
keep_alive true
log_path var/"log/mail-mcp.log"
error_log_path var/"log/mail-mcp.err"
environment_variables APPLE_MAIL_MCP_PORT: "8787", APPLE_MAIL_MCP_HOST: "localhost"
"

  # No zap stanza required
end
