# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppleMailMcp < Formula
  desc "MCP server providing programmatic access to macOS Mail.app"
  homepage "https://github.com/dastrobu/apple-mail-mcp"
  version "0.3.0"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dastrobu/apple-mail-mcp/releases/download/v0.3.0/apple-mail-mcp_0.3.0_darwin_amd64.tar.gz"
    sha256 "bebc234f501aaecaa3cab7d44187931d40805b54c2569cf3c9b438bbbf2aa0b0"

    def install
      bin.install "apple-mail-mcp"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dastrobu/apple-mail-mcp/releases/download/v0.3.0/apple-mail-mcp_0.3.0_darwin_arm64.tar.gz"
    sha256 "a5f678f56702e6edc560f2978d47f259f3bb9dd9647b77570c462b798d90cf75"

    def install
      bin.install "apple-mail-mcp"
    end
  end

  def caveats
    <<~EOS
      Apple Mail MCP Server has been installed!

      ⚠️  IMPORTANT: For proper automation permissions, you should run this server
      via launchd or brew services (not from Terminal directly).

      Option 1: Use Homebrew Services (Standard)
        brew services start apple-mail-mcp

      Option 2: Use custom launchd service (for custom port/debug)
        apple-mail-mcp launchd create

      To remove the launchd service:
        apple-mail-mcp launchd remove

      Before uninstalling with 'brew uninstall apple-mail-mcp':
        1. Stop and remove the service: brew services stop apple-mail-mcp OR apple-mail-mcp launchd remove
        2. Then run: brew uninstall apple-mail-mcp

      For more information:
        • README: https://github.com/dastrobu/apple-mail-mcp#readme
        • Docs: https://github.com/dastrobu/apple-mail-mcp/tree/main/docs
    EOS
  end

  service do
    run [opt_bin/"apple-mail-mcp", "--transport=http"]
    keep_alive true
    log_path var/"log/apple-mail-mcp.log"
    error_log_path var/"log/apple-mail-mcp.err"
    environment_variables APPLE_MAIL_MCP_PORT: "8787", APPLE_MAIL_MCP_HOST: "localhost"
  end

  test do
    system "#{bin}/apple-mail-mcp", "--version"
  end
end
