# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MailMcp < Formula
  desc "MCP server providing programmatic access to macOS Mail.app"
  homepage "https://github.com/dastrobu/mail-mcp"
  version "0.5.0"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dastrobu/mail-mcp/releases/download/v0.5.0/mail-mcp_0.5.0_darwin_amd64.tar.gz"
    sha256 "423398977385064f6623c3dbf448601b6447b3ca429bfc5256ee43a5c63b96ee"

    define_method(:install) do
      bin.install "mail-mcp"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dastrobu/mail-mcp/releases/download/v0.5.0/mail-mcp_0.5.0_darwin_arm64.tar.gz"
    sha256 "298d055c0de666af4aeb2d0372bf9f6f10f2825f92847b04bac85ddb8f297e0d"

    define_method(:install) do
      bin.install "mail-mcp"
    end
  end

  def caveats
    <<~EOS
      Apple Mail MCP Server has been installed!

      ⚠️  IMPORTANT: For proper automation permissions, you should run this server
      via launchd or brew services (not from Terminal directly).

      Option 1: Use Homebrew Services (Standard)
        brew services start mail-mcp

      Option 2: Use custom launchd service (for custom port/debug)
        mail-mcp launchd create

      To remove the launchd service:
        mail-mcp launchd remove

      Before uninstalling with 'brew uninstall mail-mcp':
        1. Stop and remove the service: brew services stop mail-mcp OR mail-mcp launchd remove
        2. Then run: brew uninstall mail-mcp

      For more information:
        • README: https://github.com/dastrobu/mail-mcp#readme
        • Docs: https://github.com/dastrobu/mail-mcp/tree/main/docs
    EOS
  end

  service do
    run [opt_bin/"mail-mcp", "run", "--transport=http"]
    keep_alive true
    log_path var/"log/mail-mcp.log"
    error_log_path var/"log/mail-mcp.err"
    environment_variables APPLE_MAIL_MCP_PORT: "8787", APPLE_MAIL_MCP_HOST: "localhost"
  end

  test do
    system "#{bin}/mail-mcp", "--version"
  end
end
